/* SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2026 Justus-Liebig-Universität Gießen
 * Author: Alexander-Lars Dallmann */
/* jc_buildrev.c -- WHICH COMMIT this binary was built from (M495).
 *
 * THE DEFECT THIS EXISTS FOR, measured 2026-08-19. The operator runs `jichi` from
 * PATH; /usr/local/bin/jichi was 12 days and ~50 milestones behind the tree, and
 * BOTH reported `jichi 0.9.0`. Nothing on screen distinguished them, so:
 *
 *   - `jichi setup --api-base ...` answered "unknown option" for a flag its own
 *     --help documents (the flag shipped at M488, after that install);
 *   - doctor's context-window check (M489) printed NOTHING AT ALL -- not a
 *     failure, not a "could not ask", just absence, which reads exactly like
 *     agreement to anyone skimming for problems.
 *
 * Half an hour went into the config before the binary was suspected. This is the
 * same argument M198 made for announcing a FAULT=1 build in --version: nobody
 * should discover which build they are running from its behaviour.
 *
 * WHY A COMMIT AND NOT A TIMESTAMP. A date makes two builds of identical sources
 * differ, which this project cares about (the snapshot work, the tier-V rigs and
 * `--dirty` all rest on "this artifact came from THAT tree"). A commit answers the
 * operator question directly -- compare it with `git rev-parse --short HEAD` -- and
 * `-dirty` answers the second one, whether uncommitted changes are baked in.
 *
 * WHY ITS OWN TRANSLATION UNIT. The value changes on every commit, so compiled into
 * main.o it would rebuild main.c (and anything else carrying the define) each time;
 * here one 20-line file rebuilds instead.
 *
 * WHY A GENERATED HEADER RATHER THAN -D. With a command-line define, make sees no
 * changed prerequisite when only the commit moves -- the .c is untouched -- so the
 * binary kept the OLD stamp after a commit. M495's own check caught that on its first
 * run. The header is a real file, so it is a real prerequisite.
 *
 * GRACEFUL WHEN THERE IS NO GIT. A tarball or a snapshot build has no repository,
 * the Makefile then defines nothing, and this returns NULL -- callers print no
 * build line at all rather than the word "unknown", because an absent stamp is
 * honest and a fake one is not. */
#include "jc_buildrev.h"

#include <stddef.h>   /* NULL */

/* Generated by the Makefile, rewritten only when the commit changes, and EMPTY when
 * there is no repository -- so JC_BUILD_REV is simply undefined there. Gitignored. */
#include "jc_buildrev_stamp.h"

const char *jc_build_rev(void)
{
#ifdef JC_BUILD_REV
    return (JC_BUILD_REV[0] != '\0') ? JC_BUILD_REV : NULL;
#else
    return NULL;
#endif
}
