#!/bin/sh
# smoke lint: the copyright holder and the licence agree everywhere, and the
# release sweep is provably complete (M497).
#
# WHAT THIS EXISTS FOR. Two failures, opposite in shape, both silent.
#
#   BEFORE the decision: a tree with no LICENSE and no headers says nothing about
#   who owns it, and silence is not neutral -- a stranger reads an unmarked public
#   repository as "presumably permissive". So every file carries the holder, and
#   an SPDX line that says LicenseRef-UNDECIDED: valid SPDX for "not on the SPDX
#   list", not the name of any licence, and therefore unmistakable for a grant.
#
#   AFTER the decision: 476 headers get swept by scripts/set-license.sh. One file
#   left saying UNDECIDED is worse than one with no header at all -- it
#   contradicts LICENSE, and a scanner that trusts headers reports the tree as
#   unlicensed. That is exactly the kind of miss no human notices in a 476-file
#   diff, which is why it is a lint and not a checklist item.
#
# So this driver is TWO-STATE and switches on one fact -- does LICENSE exist:
#
#   no LICENSE  -> every SPDX line MUST say LicenseRef-UNDECIDED   (check 7)
#   LICENSE     -> no SPDX line MAY say it, and LICENSE must be the verbatim
#                  candidate text for the identifier the headers name (7, 8, 9)
#
# It also refuses to let the release STEP rot: check 11 dry-runs
# scripts/set-license.sh, so "publishing is one command" stays a measured fact.
#
# Mostly a lint -- it reads the tree -- but checks 6 and 11 run the binary and
# the script, because "the header says X" and "the tool tells the reader X" are
# different claims and only the second one reaches a user.
. "$(dirname "$0")/_smoke.sh"

t_plan 11
tmp=$(smoke_tmp)
R="$SMOKE_ROOT"
LIC="$R/include/jc_license.h"

# THE UNIVERSE IS THE TRACKED TREE, and M546 is why.
#
# This used to `find` the working directory and exclude one path by name, with the
# comment: "include/jc_buildrev_stamp.h is generated by the Makefile and gitignored,
# so it is regenerated rather than edited and carries no header. It is the ONE
# exclusion, by construction -- not a list that can grow."
#
# The reasoning was right and the generalisation was one step away: that file is
# excluded BECAUSE IT IS GITIGNORED, and so is every other generated source. The
# list did grow -- the first time a bench left results on disk during a gate, this
# lint failed on four `.c` files THE MODEL HAD WRITTEN in throwaway workspaces
# under tests/bench/craft_ab/results/, and reported the tree as naming two licences.
#
# It had never happened before because results/ normally does not exist -- which is
# precisely how a completed frontier session was lost (M545). So the first session
# ever preserved was also the first to break this lint.
#
# `git ls-files` is the right universe: a SOURCE is something in the repository.
# It excludes the buildrev stamp for free, so the named exclusion is gone rather
# than joined by a second. The find fallback keeps the lint working in a checkout
# with no git (a released tarball, an old platform), and there it must still skip
# generated trees explicitly.
c_files() {
    if git -C "$R" rev-parse --git-dir >/dev/null 2>&1; then
        git -C "$R" ls-files -- src include tests 2>/dev/null \
            | grep -E '\.(c|h)$' | sed "s|^|$R/|" | sort
    else
        find "$R/src" "$R/include" "$R/tests" \( -name '*.c' -o -name '*.h' \) \
            2>/dev/null | grep -v 'jc_buildrev_stamp.h' \
            | grep -v '/results/' | sort
    fi
}

# ---- 1. the floor: the scan finds the tree, and the matcher works -----------
# Two empty sets agree perfectly, so a lint over "every C file" must first prove
# it found the C files. 476 today; the floor is deliberately far below that so
# real growth never trips it, and a broken find does.
_n=$(c_files | wc -l | tr -d '[:space:]')
mkdir -p "$tmp/self"
printf '/* SPDX-License-Identifier: X\n * Copyright (c) 2026 Y */\n' \
    > "$tmp/self/good.h"
printf '/* no header here */\n' > "$tmp/self/bad.h"
_hits=$(grep -L 'SPDX-License-Identifier' "$tmp/self"/*.h 2>/dev/null \
    | wc -l | tr -d '[:space:]')
if [ "$_n" -ge 400 ] && [ "$_hits" -eq 1 ]; then
    t_ok "scanning $_n C sources; the header matcher flags a planted positive"
else
    t_fail "floor tripped: found $_n C sources (expect >= 400) and the matcher \
flagged $_hits of 2 planted files (expect 1) -- fix the extraction, not the floor"
fi

# ---- 2. every source carries an SPDX line, and they all name ONE licence ----
# "Some files say A and some say B" is the state that makes a tree unusable for
# a downstream packager, so mixed identifiers fail as loudly as missing ones.
: > "$tmp/missing"
c_files | while read -r f; do
    head -n 1 "$f" | grep -q '^/\* SPDX-License-Identifier: ' || \
        echo "${f#$R/}" >> "$tmp/missing"
done
_miss=$(wc -l < "$tmp/missing" 2>/dev/null | tr -d '[:space:]')
[ -n "$_miss" ] || _miss=0
_ids=$(c_files | while read -r f; do
    head -n 1 "$f" | sed -n 's|^/\* SPDX-License-Identifier: \(.*\)$|\1|p'
done | sort -u)
_nids=$(printf '%s\n' "$_ids" | grep -c .)
if [ "$_miss" -eq 0 ] && [ "$_nids" -eq 1 ]; then
    t_ok "all $_n sources carry one SPDX identifier: $_ids"
else
    t_fail "$_miss source(s) with no SPDX first line, and $_nids distinct \
identifier(s) [$(printf '%s' "$_ids" | tr '\n' ' ')]. A tree that names two
licences cannot be packaged.$([ "$_miss" -gt 0 ] && { printf '\n%s\n' \
"First files with no header:"; head -n 5 "$tmp/missing"; })"
fi
ID=$(printf '%s\n' "$_ids" | head -n 1)

# ---- 3. one copyright holder, spelled identically everywhere ----------------
# A drifting holder line (a year that moved, a name abbreviated in 40 files) is
# the same defect as a drifting licence: it makes ownership arguable.
HOLDER=$(sed -n 's|^#define JC_COPYRIGHT "\(.*\)"$|\1|p' "$LIC")
# M619: the holder (line 2) and the author (line 3, closing the block) are two
# lines with two meanings -- § 69b UrhG: the employer exercises the economic
# rights, authorship stays with the author -- and both must be spelled
# identically everywhere, or ownership and attribution become arguable.
AUTHOR=$(sed -n 's|^#define JC_AUTHOR "\(.*\)"$|\1|p' "$LIC")
: > "$tmp/badc"
c_files | while read -r f; do
    grep -q "^ \* $HOLDER\$" "$f" && grep -q "^ \* $AUTHOR \*/\$" "$f" \
        || echo "${f#$R/}" >> "$tmp/badc"
done
_badc=$(wc -l < "$tmp/badc" 2>/dev/null | tr -d '[:space:]')
[ -n "$_badc" ] || _badc=0
if [ -n "$HOLDER" ] && [ -n "$AUTHOR" ] && [ "$_badc" -eq 0 ]; then
    t_ok "every source names one holder + one author: $HOLDER / $AUTHOR"
else
    t_fail "holder='$HOLDER' author='$AUTHOR'; $_badc source(s) do not carry \
both (holder on line 2, author closing the block):
$(head -n 5 "$tmp/badc")"
fi

# ---- 4. the headers and the C constant cannot disagree ----------------------
# jc_license.h is what --version and describe print. If the headers were swept
# and the define was not, the tool would advertise a licence the files deny.
_def=$(sed -n 's|^#define JC_LICENSE_SPDX "\(.*\)"$|\1|p' "$LIC")
if [ -n "$_def" ] && [ "$_def" = "$ID" ]; then
    t_ok "JC_LICENSE_SPDX agrees with the file headers ($ID)"
else
    t_fail "include/jc_license.h says '$_def'; the headers say '$ID' -- the \
sweep touched one and not the other"
fi

# ---- 5. the candidate texts have not drifted -------------------------------
# Nobody reads 11 KB of legal text in a diff. A checksum does.
if command -v sha256sum > /dev/null 2>&1; then
    (cd "$R/docs/licenses" && sha256sum -c SHA256SUMS > "$tmp/sums" 2>&1); _src=$?
    _cnt=$(grep -c . "$R/docs/licenses/SHA256SUMS")
    if [ $_src -eq 0 ] && [ "$_cnt" -ge 2 ]; then
        t_ok "$_cnt candidate licence file(s) match their recorded checksums"
    else
        t_fail "sha256sum -c rejected the candidate texts (rc=$_src, $_cnt \
recorded). A licence text that has drifted is not that licence:
$(grep -v ': OK$' "$tmp/sums" | head -n 4)"
    fi
else
    t_skip_one "no sha256sum on this host; candidate texts unverified"
fi

# ---- 6. the READER is told, by the tool, not just by the source -------------
"$BIN" --version > "$tmp/ver" 2>&1
"$BIN" describe --output json > "$tmp/desc" 2>/dev/null
if grep -q "^$HOLDER\$" "$tmp/ver" && grep -q "^$AUTHOR\$" "$tmp/ver" &&
   grep -q "^licence: $ID\$" "$tmp/ver" &&
   grep -q "\"license\":\"$ID\"" "$tmp/desc" &&
   grep -q "\"copyright\":\"$HOLDER\"" "$tmp/desc" &&
   grep -q "\"author\":\"$AUTHOR\"" "$tmp/desc"; then
    t_ok "--version and describe report the holder, the author and $ID"
else
    t_fail "the binary does not report what the tree says. --version:
$(head_bytes 200 "$tmp/ver")
describe license field: $(sed -n 's/.*\("license":"[^"]*"\).*/\1/p' "$tmp/desc")"
fi

# ---- 7. THE TWO-STATE CHECK ------------------------------------------------
# One check, two assertions, chosen by the one fact that decides which is right.
# This is the check that fails a release with a half-finished sweep, so it counts
# the FILES that still say UNDECIDED rather than reading the aggregate identifier
# from check 2: with 475 files swept and one missed, the aggregate is the new
# licence and only a count sees the straggler. (Check 2 fails too -- mixed
# identifiers -- but "one distinct id too many" is a worse diagnosis to be handed
# on release day than "these 1 file(s) were missed".)
: > "$tmp/undec"
c_files | while read -r f; do
    head -n 1 "$f" | grep -q 'LicenseRef-UNDECIDED' && echo "${f#$R/}" >> "$tmp/undec"
done
_und=$(wc -l < "$tmp/undec" 2>/dev/null | tr -d '[:space:]')
[ -n "$_und" ] || _und=0
if [ -f "$R/LICENSE" ]; then
    if [ "$_und" -eq 0 ]; then
        t_ok "LICENSE exists and no source still says UNDECIDED ($ID)"
    else
        t_fail "LICENSE exists but $_und source(s) still say \
LicenseRef-UNDECIDED -- the headers contradict the licence file, and a scanner \
that reads headers will call this tree unlicensed. Re-run \
scripts/set-license.sh <spdx-id>. Missed:
$(head -n 5 "$tmp/undec")"
    fi
else
    if [ "$_und" -eq "$_n" ]; then
        t_ok "no LICENSE, and all $_n sources say so (LicenseRef-UNDECIDED)"
    else
        t_fail "there is no LICENSE file, but only $_und of $_n sources say \
UNDECIDED -- the rest claim '$ID', and a licence named only in a comment grants \
nothing and cannot be relied on"
    fi
fi

# ---- 8. LICENSE is the verbatim candidate text, not a paraphrase ------------
if [ -f "$R/LICENSE" ]; then
    if [ -f "$R/docs/licenses/$ID.txt" ] &&
       cmp -s "$R/LICENSE" "$R/docs/licenses/$ID.txt"; then
        t_ok "LICENSE is byte-identical to docs/licenses/$ID.txt"
    else
        t_fail "LICENSE does not match docs/licenses/$ID.txt (or that file is \
absent) -- a modified licence text is not that licence"
    fi
else
    t_skip_one "no LICENSE yet: nothing to compare against a candidate text"
fi

# ---- 9. the NOTICE a licence propagates is installed -----------------------
# Apache-2.0 section 4(d) carries NOTICE into every redistribution. Shipping the
# licence without the NOTICE it names is an incomplete release.
if [ -f "$R/LICENSE" ] && [ -f "$R/docs/licenses/NOTICE.$ID" ]; then
    if cmp -s "$R/NOTICE" "$R/docs/licenses/NOTICE.$ID"; then
        t_ok "NOTICE is installed and matches the $ID template"
    else
        t_fail "$ID propagates a NOTICE file and this tree has none (or it has \
drifted from docs/licenses/NOTICE.$ID)"
    fi
else
    t_skip_one "no LICENSE, or $ID has no NOTICE template: nothing required"
fi

# ---- 10. the page a reader is sent to agrees with the state -----------------
# docs/LICENSING.md is the ONE page that makes a claim about the current state.
# A bare "does it mention $ID" would be vacuous there: that page DISCUSSES
# Apache-2.0 at length whatever is in force, so it would pass on the day the
# sweep ran and the table did not. So the claim lives in one parseable row,
# set-license.sh rewrites exactly that row, and this reads it back.
_row=$(sed -n 's#^| SPDX identifier in force | `\(.*\)` |$#\1#p' \
    "$R/docs/LICENSING.md")
if [ -n "$_row" ] && [ "$_row" = "$ID" ]; then
    t_ok "docs/LICENSING.md states the identifier in force ($ID)"
else
    t_fail "docs/LICENSING.md's 'SPDX identifier in force' row says '$_row', \
the tree says '$ID' -- the page a reader is sent to describes a state the tree \
has left (or the row was renamed and this check now reads nothing)"
fi

# ---- 11. the release step still works -------------------------------------
# "Publishing is one command" is a claim about a script, and an untested script
# is a claim. The dry run touches nothing; the refusal proves it will not invent
# a licence text. Both assert on the REASON, never on the exit status alone.
"$R/scripts/set-license.sh" --dry-run Apache-2.0 > "$tmp/dry" 2>&1; _rc1=$?
"$R/scripts/set-license.sh" NoSuchLicence-9.9 > "$tmp/ref" 2>&1; _rc2=$?
if [ $_rc1 -eq 0 ] && grep -q 'DRY RUN, nothing written' "$tmp/dry" &&
   grep -q 'would copy docs/licenses/Apache-2.0.txt to LICENSE' "$tmp/dry" &&
   [ $_rc2 -ne 0 ] && grep -q 'no verbatim text' "$tmp/ref"; then
    t_ok "set-license.sh dry-runs a real candidate and refuses an invented one"
else
    t_fail "release step broken: dry-run rc=$_rc1 '$(head_bytes 120 "$tmp/dry")' \
refusal rc=$_rc2 '$(head_bytes 120 "$tmp/ref")'"
fi

t_done
