"""The truth for tags.py. Do not edit this file -- fix the function."""
import unittest

from tags import add_tag


class TestAddTag(unittest.TestCase):
    def test_single(self):
        self.assertEqual(add_tag("draft"), ["draft"])

    def test_independent_calls(self):
        add_tag("draft")
        self.assertEqual(add_tag("final"), ["final"])

    def test_explicit_list(self):
        self.assertEqual(add_tag("c", ["a", "b"]), ["a", "b", "c"])


if __name__ == "__main__":
    unittest.main()
