"""The specification for freq.py, written as tests. Do not edit this file.

Read it as the requirements document it is: every assertion is a sentence
about what your code must do, and the whole suite is the acceptance criteria.
"""
import unittest

from freq import top_n, word_counts


class TestWordCounts(unittest.TestCase):
    def test_counts_words_case_insensitively(self):
        self.assertEqual(word_counts("The the THE cat"), {"the": 3, "cat": 1})

    def test_splits_on_punctuation(self):
        self.assertEqual(word_counts("cat, dog; cat."), {"cat": 2, "dog": 1})

    def test_ignores_digits_and_symbols(self):
        self.assertEqual(word_counts("a1 b! 2"), {"a": 1, "b": 1})

    def test_empty_text(self):
        self.assertEqual(word_counts(""), {})


class TestTopN(unittest.TestCase):
    def test_orders_by_count_descending(self):
        counts = {"a": 1, "b": 3, "c": 2}
        self.assertEqual(top_n(counts, 2), [("b", 3), ("c", 2)])

    def test_ties_break_alphabetically(self):
        counts = {"pear": 2, "apple": 2, "fig": 1}
        self.assertEqual(top_n(counts, 2), [("apple", 2), ("pear", 2)])

    def test_n_larger_than_the_data(self):
        self.assertEqual(top_n({"only": 1}, 5), [("only", 1)])

    def test_n_is_zero(self):
        self.assertEqual(top_n({"a": 1}, 0), [])


if __name__ == "__main__":
    unittest.main()
