/* The as-found snapshot of journal.c. The grader compiles YOUR trim test
 * against this copy: a real proof-test must FAIL here and PASS on your
 * fixed journal.c. Do not edit this file. */
/* journal.c - see journal.h. */
#include "journal.h"

#include <string.h>

void journal_init(struct journal *j)
{
    j->count = 0;
}

int journal_append(struct journal *j, const char *text)
{
    size_t n;
    if (j->count >= JOURNAL_MAX) {
        return -1;
    }
    n = strlen(text);
    if (n >= NOTE_MAX) {
        n = NOTE_MAX - 1;
    }
    memcpy(j->notes[j->count], text, n);
    j->notes[j->count][n] = '\0';
    j->count++;
    return 0;
}

size_t journal_count(const struct journal *j)
{
    return j->count;
}

const char *journal_get(const struct journal *j, size_t i)
{
    if (i >= j->count) {
        return NULL;
    }
    return j->notes[i];
}

const char *journal_find(const struct journal *j, const char *word)
{
    size_t i;
    for (i = 0; i < j->count; i++) {
        if (strstr(j->notes[i], word) != NULL) {
            return j->notes[i];
        }
    }
    return NULL;
}

void journal_trim(struct journal *j, size_t keep)
{
    size_t drop;
    size_t i;
    if (keep >= j->count) {
        return;
    }
    /* Shift the survivors down over the discarded oldest notes. */
    drop = j->count - keep;
    for (i = 0; i + drop < j->count; i++) {
        memcpy(j->notes[i], j->notes[i + drop - 1], NOTE_MAX);
    }
    j->count = keep;
}
