"""The safety net. Green before your refactor and green after it.

Do not edit this file: a refactor that needs its tests changed is not a
refactor, it is a behaviour change wearing one as a disguise.
"""
import unittest

from report import even_squares, name_lengths, unique_initials


class TestReport(unittest.TestCase):
    def test_even_squares(self):
        self.assertEqual(even_squares([1, 2, 3, 4, 5, 6]), [4, 16, 36])

    def test_even_squares_empty(self):
        self.assertEqual(even_squares([]), [])

    def test_even_squares_none_even(self):
        self.assertEqual(even_squares([1, 3, 5]), [])

    def test_name_lengths(self):
        self.assertEqual(name_lengths(["ada", "grace"]), {"ada": 3, "grace": 5})

    def test_name_lengths_empty(self):
        self.assertEqual(name_lengths([]), {})

    def test_unique_initials(self):
        self.assertEqual(unique_initials(["ada", "alan", "grace"]), {"A", "G"})


if __name__ == "__main__":
    unittest.main()
